In [1]:
import numpy as np
import scipy.io as scio

# 用 scipy.io 讀取 .mat 格式的資料集
offline_data = scio.loadmat('offline_data_random.mat')
online_data = scio.loadmat('online_data.mat')

X_train = offline_data['offline_rss']
Y_train = offline_data['offline_location']
X_test = online_data['rss']
Y_test = online_data['trace']

print(X_train)
print(Y_train)

[[-54.29619915 -55.84492426 -57.70509902 -46.80467167 -47.18452432
  -56.77109825]
 [-58.03786    -51.3649     -42.8752726  -70.98668596 -58.49786736
  -55.93776941]
 [-59.95815356 -51.09653955 -61.88934484 -52.36408345 -49.49788981
  -48.88895675]
 ...
 [-53.40874158 -60.84021556 -51.23357536 -51.38278381 -35.88665949
  -50.50031336]
 [-52.77725195 -48.65652017 -61.70492883 -52.52360053 -51.09924776
  -61.54001236]
 [-58.46378652 -55.5427065  -50.90296116 -57.43968404 -60.20844646
  -49.26780849]]
[[ 556 1361]
 [1816  351]
 [1153  859]
 ...
 [ 994 1475]
 [ 843  752]
 [1814  756]]


In [2]:
# 區域對應
labels = np.round(Y_train[:,0]/100)*100 + np.round(Y_train[:,1]/100)
print(Y_train)
print(labels)

[[ 556 1361]
 [1816  351]
 [1153  859]
 ...
 [ 994 1475]
 [ 843  752]
 [1814  756]]
[ 614. 1804. 1209. ... 1015.  808. 1808.]


In [5]:
# from sklearn import neighbors
# knn = neighbors.KNeighborsClassifier(n_neighbors=10)
# knn.fit(X_train, Y_train)
# print(knn)

KNeighborsClassifier(n_neighbors=10)


In [6]:
from sklearn import neighbors
knn = neighbors.KNeighborsClassifier(n_neighbors=10)
knn.fit(X_train, labels)
print(knn)

KNeighborsClassifier(n_neighbors=10)


In [7]:
p = knn.predict(X_test)
print("predict:\n", p)
labels_test = np.round(Y_test[:,0]/100)*100 + np.round(Y_test[:,1]/100)
print("true_labels:\n", labels_test)

predict:
 [1612. 1409.  208. ...  404.  104.  307.]
true_labels:
 [1511. 1510. 1510. ...  206.  206.  307.]
